version: "2"
services:
  nginx:
    image: nginx:alpine
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./environment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./environment/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8083:80

  magento:
    image: vitormarcelino/magento2-environment
    restart: always
    working_dir: /var/www/html
    expose:
      - 9000
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: Magento2021!
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    restart: always
    environment:
      - discovery.type=single-node
volumes:
  data:
